tool_name = 'materialx'
report_type = 'default'
target_configuration = 'MaterialX'
images_diff_threshold = 1000
compare_images = False
fail_if_diff_time = False
show_render_time = False
show_sync_time = False
show_execution_time = True
show_render_log = False
show_performance_tab = False
configurations_order = ["MaterialX", "HybridPro", "Northstar"]